NumPy (Numerical Python) is a library used for:

Working with arrays

Performing mathematical operations

Fast scientific computing

It is much faster than Python lists for numerical data and uses less space

in Numpy we have different Dimensions - 1Dimension array - [1,2,3,4] 2Dimension[[1,2,3,4],[5,6,7,8]] and 3D [[[1,2,3],[4,5,6],[7,8,9]]]

np.array() - comverts a list into array
ndim - gives output as nth dimensions - means how much dimension is it 
np.zeroes() - gives us a zero array 


In [1]:
import numpy as np

In [2]:
np_array = np.array([1,2,3,4])

In [3]:
print(type(np_array)) #type of this array is np array

<class 'numpy.ndarray'>


In [4]:
#why we dont use list ? because 

list1 = [1,2,3,4]
list2 = [5,6,7,8]

list3 = list1+list2
print(list3) #this is not giving us sum of two lists list is just appending both lists

[1, 2, 3, 4, 5, 6, 7, 8]


#now same example with numpy

In [9]:
list3 = np.array([1,2,3,4])
list4 = np.array([5,6,7,8])
list5 = list3+list4
print(list5) # see numpy actually added and gave out sum simililarly we can do substraction , multiplication division etc but not in lists


[ 6  8 10 12]


In [10]:
list6 = np.array([1,2,3,4])
list7 = np.array([5,6,7,8])
list8 = list6*list7
print(list8)

[ 5 12 21 32]


In [12]:
#lets try with 2d array muliplied with 1d array

list9 = np.array([[1,2,3,4],[2,2,2,2]])
list10 = np.array([5,6,7,8])
list11 = list9*list10
list11

array([[ 5, 12, 21, 32],
       [10, 12, 14, 16]])

In [ ]:
#lets try with 2d array muliplied with 2d array

In [6]:
list12 = np.array([[1,2,3,4],[2,2,2,2]])
list13 = np.array([[5,6,7,8],[2,2,2,2]])
list14 = list12*list13
list14
#print(list12.ndim)

array([[ 5, 12, 21, 32],
       [ 4,  4,  4,  4]])

Next -> Array Indexing, Slicing, Shape, and Reshape — these are used constantly in data science and machine learning.

#1️⃣ NumPy Array Indexing

#Indexing means accessing a specific element from an array.

In [14]:
np_array = np.array([1,2,3,4,5,6,7,8,9]) # this is 1D array

In [17]:
print(np_array[0]) #first element starts from 0
print(np_array[-1]) #last element starts from -1

1
9


In [25]:
np_2d_array = np.array([[1,2,3,4],
                      [9,8,7,6]])

np_2d_array.ndim
np_2d_array[0,1] # 0th row and 1st column

2

3️⃣ Array Slicing

Slicing means selecting a range of elements.

array[start:end] - >> this is for 1D array
arr[row_start:row_end , col_start:col_end] ---->>> this is for 2D array
here array variable holds np array

In [32]:
np_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np_array[1:7]

array([2, 3, 4, 5, 6, 7])

In [36]:
list11

array([[ 5, 12, 21, 32],
       [10, 12, 14, 16]])

In [38]:
list11[0:,2:4]# here we have 2 rows 0 and 1 but 1 is not included hence we did 0:and then col 4 is not included hence we did 0:4

array([[21, 32],
       [14, 16]])

Shape

In [40]:
list11.ndim #to check dimensions

2

In [41]:
list11.shape # to check shape on array 2 rows and 4 cols

(2, 4)

In [19]:
test_array = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

test_array.ndim

2

In [17]:
# Que - print element 6

test_array[1,2] # first row and 2nnd col

6

# why numpy is fast and how memory allocation is done ?

Numpy is fast due to :
1) continuous memory allocation because it stores same datatypes 
but in list we can put many data types and it doesnot store in continous memory locations but in random 

2) while searching in np array whole array is scanned at once however in list a loop works


🎯 Why NumPy is Fast

Because it uses:

C language implementation

Vectorized operations ---- Instead of loops, NumPy processes the entire array at once.

Continuous memory layout

No Python loops --

Broadcasting - NumPy can operate on arrays of different sizes.

### Here are 10 powerful tricks in NumPy

1️⃣ Boolean Filtering (Very Useful) - where array>10
2️⃣ where() Function --- used in filter  np.array and np..where ()
3️⃣ Random Numbers - create random array np.random.rand(2,3)
4️⃣ Random Integers - create random integers - np.random.randint(low, high, size) creates random integers
5️⃣ Unique Values - find unique values - distinct
6️⃣ Sorting Arrays - sorting 
7️⃣ Stacking Arrays - Combine arrays vertically or horizontally.
8️⃣ Flatten Array - convert matrix to 1d
9️⃣ Find Maximum and Minimum
🔟 Axis Operations (VERY IMPORTANT) 0 axis is up down and 1 axis is left to right

In [11]:
np_array

array([1, 2, 3, 4])

In [14]:
new_array_indices = np.where(np_array > 2) # where condition will give indices of elements which are greater or less than something
new_array_indices
print(np_array[new_array_indices]) #here we are printing actual values of indices

[3 4]


In [43]:
np_array[np_array>6]  #Boolean Filtering

array([7, 8, 9])

In [52]:
np_array = np.array([2,5,7,9,3])

np.where(np_array > 6) # 2 and 3 are the indexes where conditions is true


(array([2, 3], dtype=int64),)

In [53]:
np.random.rand(2,3) # random matrix two rows and 3 cols

array([[0.89928785, 0.3906043 , 0.85598707],
       [0.71470731, 0.52337076, 0.63362013]])

In [57]:
np.random.randint(1,10,(2,2)) # between 1 to 10 and 2 by 2 matrix

array([[8, 5],
       [4, 9]])

In [60]:
new_array = np.array([1,1,1,3,3,3,4,5,5,5,5])

In [63]:
np.unique(new_array) # finding distinct values from array


array([1, 3, 4, 5])

In [42]:
new_array
np.sort(new_array) #this is by default asc if you want to do desc then [::-1

array([[2, 3]], dtype=int64)

In [69]:
np.sort(new_array)[::-1] #sorted backwards or in desc

array([5, 5, 5, 5, 4, 3, 3, 3, 1, 1, 1])

In [73]:
a = np.array([1,2,3]) #two 1D array converted into 1 2d array
b = np.array([4,5,6])

nw = np.vstack((a,b))

In [72]:
a.ndim

1

In [74]:
nw.ndim

2

In [75]:
nw.flatten() # converted 2D array into 1D array

array([1, 2, 3, 4, 5, 6])

In [77]:
a.max() #maximum from a array

3

In [78]:
a.min() #minimum from a array

1

In [79]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [80]:
np.sum(arr,axis =0 ) #axis 0 means sum of top to bottom

array([5, 7, 9])

In [82]:
np.sum(arr,axis = 1) #axis 1 menas sum of left to right

array([ 6, 15])

The numpy.arange() function (commonly referred to as np.arange()) is a powerful tool in Python's NumPy library used to create an array with evenly spaced values within a specified interval. It functions similarly to Python's built-in range() function but returns a NumPy ndarray

In [23]:
np.arange(4,8)

array([4, 5, 6, 7])

In [31]:
#Que What is the shape of an array created using np.zeros((3, 4))?

x = np.zeros((3,4))
print(x.shape)

(3, 4)


In [32]:
b = np.arange(4,8)

In [33]:
b

array([4, 5, 6, 7])

The
numpy.linspace() function is a core tool in the NumPy library for Python, used to create an array of a specified number of evenly spaced values over a defined interval. It is particularly useful for plotting graphs, mathematical computations, and data simulations. 

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)


In [40]:
b = np.linspace(1,2,num = 5) #between 1 and 2 create 5 equal partitions 

In [41]:
b

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

✅ What You’ve Learned

NumPy basics

Installation and import (import numpy as np)

Creating arrays (np.array, np.zeros, np.ones, np.arange, np.random)

Array dimensions

1D, 2D, 3D arrays

.shape, .ndim, .size

Indexing & slicing

1D, 2D, and 3D arrays

Boolean indexing (arr[arr > 5])

Reshape & flatten

.reshape(), .flatten()

Random numbers

np.random.rand(), np.random.randint()

Mathematical operations

+, -, *, / on arrays (vectorization)

np.sum, np.mean, np.max, np.min, axis usage

Advanced beginner tricks

np.where()

Sorting (ascending/descending)

Stacking (vstack, hstack)

Unique values (np.unique())